build/constraints.js
build/spot.js
constraints/nonrecursivity.js
interface1.html

Added nonRecParent and nonRecPairs to interface.
Changed name of nonRec1 to nonRecChild so tableau would be more informative.

NonRecursivity Interface Updates

---

candidategenerator.js
interface1.html
interface1.js
tableauMaker.js
test/toneOptions.html
treeFormatting.js
trees/toneOptions.js

Works out the kinks in tone annotations with new options and parentheses.

Tones options

---

interface1.html
interface1.js

Reverts syntax-prosody-ot/main#133 since it was merged by accident

Revert "Collapsible interface"

---

interface1.html
interface1.js

Show code button toggles the code section.

Show code button to show converted trees to JavaScript

---

built-in_analyses.js
interface1.html
interface1.js

Removed checkboxes and updated functionality for the Prosodic Categories GEN options

Gen categories update

---

interface1.html
interface1.js
tableauMaker.js

Since this branch is based on save-load_analysis, I figured it would be best to merge it into that branch instead of opening a pull request to the interface-reorg branch, which has an open pull request to merge the save-load_analysis branch into it

Hide Prosodic Categories option in Interface

---

built-in_analyses.js
constraints/match.js
interface1.html
interface1.js

Merging in changes to built-in analysis that deal with constraint reorganization

Save load analysis

---

constraints/match.js
interface1.html
interface1.js

div based solution applied to all constraints

Constraint div

---

built-in_analyses.js
constraints/match.js
interface1.html
interface1.js
tableauMaker.js

clear button closes open fieldsets.

Clear close fieldset

---

interface1.js

done message disappears when tree id is edited

---

interface1.html

made spotBlock responsive to long trees

---

interface1.html

adding match instructions

---

interface1.html

added alignPS to interface

---

interface1.html
interface1.js

Issue #239 
Is button placement and styling ok?

added button to clear previous tableaux

---

built-in_analyses.js

* updated ICPP built-in analyses so GEN produces trees that are rooted in phi; apparently I had already added that functionality to the built-in analyses but had forgotten about it.
* updated built-in systems to load options with a drop-down selector
* updated clearAll() to clear options with a drop-down slector
* updated save analysis to save options with a drop-down selector

Built in system updates

---

constraints/alignLeftMorpheme.js
interface1.js

replaced space with underscore for alignLeftMorpheme category

---

interface1.js

The whole tree should be searched. If a node in the tree builder is marked as func or silentHead, an attribute is added to that node and the category is renamed to not include the func or silentHead labels.

Functional silent nodes

---

treeFormatting.js

I need to edit treefromatting.js to show head marking  so that i can more easily test that the headmarking is doing what it is supposed to

Parenthesize tree to japaneseHeadMarking

---

interface1.html

I keep forgetting to open a pull request for this.

Typo fixed

---

treeFormatting.js

This branch cherry-picked the contentful commits from parenthesize-tree in order to fix the version history.

New parenthesize tree

---

interface1.html

Under balancedSisters, phi is checked by default.

phi is checked by default

---

interface1.html
interface1.js
treeFormatting.js
treeTrimming.js

Trying to merge Max's feature branch back into Iva's...

S cat conflation interface

---

built-in_analyses.js
interface1.html
interface1.js

Update sCat_conflation_interface from constraint_hierarchy -- still has merge conflicts though

Constraint hierarchy

---

interface1.js

I just redid the fix for overriding terminals that got overwritten by another merge.

redoing fix for overriding terminals, issue #245

---

interface1.html
interface1.js

Issue #285 
I'm not sure if this is how you wanted the warning for using hyphens or underscores in category and id names to work, let me know if it should be different or what the message should be.

Clitic problems

---

inputCandidateGenerator.js
interface1.html
interface1.js
syntaxFilters.js

Reverts syntax-prosody-ot/main#340 -- need to fix the mirror option first before we do this merge.

Revert "Input gen options"

---

inputCandidateGenerator.js
interface1.html
interface1.js
syntaxFilters.js

Reverts syntax-prosody-ot/main#346
Didn't mean to actually merge these but somehow it happened by accident

Revert "Update input-gen-options from  master"

---

inputCandidateGenerator.js
interface1.html
interface1.js
syntaxFilters.js

Input gen options

---

analysis_html_files/compound_w_gen_AndrewA.html
constraints/alignWrap.js
inputCandidateGenerator.js
interface1.html
syntaxFilters.js
test/alignAndExhaustTest.html

Reverts syntax-prosody-ot/main#352
Accidentally updated master which was not at all intended!

Revert "update from master"

---

candidategenerator.js
test/gen_cat_test.html

fix duplicates in GEN results

---

constraints/alignWrap.js
test/alignAndExhaustTest.html

Align focus

---

interface1.html

added linearity to interface

---

constraints/noShift.js
interface1.html
test/noShiftGradientTest.html

I tested it in noShiftGradientTest.html with the examples that Nick gave in the issue. The function in that file is the same as the noShiftGradient function in noShift.js, I just modified it to take in the lists of terminals so I didn't have to make all the trees to test it. What other cases should I test? Issue #293

Gradient noShift

---

candidategenerator.js
constraints/binarity.js
interface1.html
interface1.js
test/maxBranchingTest.html

Issue #249. In the test file maxBranchingTest.html I have trees {a b} and {a b c}. When the variable max_branches is 2, it excludes some candidates from {a b c} and none from {a b}. The excluded candidates are written to the console.

maxBranching GEN option

---

candidategenerator.js
interface1.html
interface1.js
test/multi-clitic_test.html

The old branch was all messed up, so I made a fresh one ... again. This closes issue #360 and #242, and replaces pull request #326.

New clitic movement

---

candidategenerator_wrapper.js
trees/built-in_trees.js

syntax sensitivity for clitics

---

built-in_analyses.js
interface1.js

built-in analysis opens only manual input parameters

---

trees/built-in_trees.js
trees/chamorro_clitic_trees.js

trees were being redefined in another file

chamorro_clitic_trees problem

---

built-in_analyses.js
candidategenerator.js
candidategenerator_wrapper.js
constraints/alignMorpheme.js
constraints/noShift.js
constraints/nonrecursivity.js
inputCandidateGenerator.js
interface1.html
interface1.js
prosodicHierarchy.js

'new-error-handling' is just a copy of master

merge 'error-handling' changes into 'new-error-handling'

---

inputCandidateGenerator.js
interface1.html
interface1.js
prosodicHierarchy.js

It seems like it's working on the interface, but I can write a test file if needed. 
Closes issue #278

Allow clitics option

---

interface1.html

increased button font size

---

interface1.html

reorder sections on interface

---

interface1.html
treeFormatting.js

accent labeling

---

inputCandidateGenerator.js
interface1.html
interface1.js
syntaxFilters.js
test/containsAdjunctTest.html
test/threeXPsTest.html

Bar levels option

---

interface1.html

change default gen to manual

---

constraints/binarity.js
test/binMaxHeadTest.html

Bin max head

---

inputCandidateGenerator.js
interface1.html
interface1.js

Syntax parameters

---

inputCandidateGenerator.js

reordering noAdjuncts

---

interface1.js

fix disabled head reqs for x0 as intermediate node

---

interface1.html
interface1.js

Terminal strings interface

---

tableauMaker.js

don't throw error when cat is undefined

---

built-in_analyses.js
constraints/strongStart.js
interface1.html
test/strongStartCatInit.html
trees/AMP2020_irish_trees.js

Necessary back-end for Irish built-in system for AMP. Defines strongStart_catInit() and tests. All appears to be working

strongStartCatInit function

---

constraints/headedness.js
interface1.html
test/headednessConstraint.html

Adding headedness constraint to interface1.html

Headedness constraint

---

constraints/alignWrap.js
constraints/annotate_tones.js
constraints/japaneseAccent.js
test/japaneseTest2.html

Fix bugs with accentFromId() which were impacting accentAsHead and noLapseL. Also minor fixes to wrap() and to addJapaneseTones() in annotate_tones.js.

Accent bugs

---

test/_test_template.html

I started the file with "_" so it would rise to the top of the directory

Mocha testing tempalte

---

interface1.js

Inputs of more than 6 terminals warning show only once

input 6 terminals

---

interface1.html

Improve info about head marking on interface

Head marking interface

---

jsbuild.bat

-Added line to build files in interface_JS folder into build/interface.js
-Changed line to include interface.js in spot.js
Looks like it works? All the files seem to be properly built into spot.js

jsbuild.bat modified

---

constraints/strongStart.js
interface1.html
interface_JS/interface_display_helpers.js
jsbuild.bat
test/strongStartHsuTest.html

Fully functional with automated test document

Strong start categories

---

constraints/strongStart.js
interface1.html
test/strongEndTest.html
test/strongEndTest.js
test/weakStartTest.html
test/weakStartTest.js

Weak start and strong End

---

.github/workflows/test-spot-frontend.yml

Frontend testing

---

constraints/binarity.js
constraints/recursiveCatEvals.js
interface1.html
interface_JS/interface_display_helpers.js
interface_JS/interface_load.js
test/binMaxHeadTest.js

redone from binMinHead branch due to merge conflicts and complications in testing file

add binMinHead
