syntax-prosody-ot/main

constraints/ctConstraints.js
The file ctConstraints.js contains Command-Theoretic constraints and
the new helper functions they rely on. I've removed the redundant getleaves(), and changed the name of split() since that's a reserved word.
=> Constraints for Command Theory

build/constraints.js, build/spot.js, constraints/binarity.js, constraints/nonrecursivity.js, interface1.html, test/binTest.html
Generalized leaf-counting binarity constraints and added updated constraints to the interface.
I had to mess with getDescendantsOfCat (helper function in binarity.js) since it only actually counted terminal nodes of the specified category. Details in commit history and comment within code.
Tests look good, constraints are assigning the correct number of violations now.
=> Bin--Leaves constraints

build/constraints.js, build/spot.js, constraints/match.js, test/matchOrdering.html
I used the branch Match_Ordering_Update to make match constraints order insensitive in preparation for terminal re-ordering analyses, but since this branch was dependent on MatchMax, I decided it would be more efficient to merge Match_Ordering_Update into MatchMax instead of making another pull request for merging the update branch into master.
=> Updates to match and matchMax for order-sensitivity

interface1.html
Accentedness constraints are now in a table with the css class "constraint-selection-table," which makes them small caps and the same indentation as earlier constraints. Moved content of info buttons so that it displays when you mouse-over the constraint.
=> changed accentAsHead and noLapse-L into a constraint-selection-table

candidategenerator.js, interface1.js, tableauMaker.js, test/irish_tone_annotation_test.html, treeFormatting.js
It turns out the issues with Irish tone annotation were only happening when it was called from GEN. I eliminated this issue by changing the code to only call tone annotation functions from parenthesizeTree instead of calling them from GEN.
=> Irish tones

interface1.js
Bug fixed: when "Annotate with Tones" is selected then "Tree Display Options" is closed, the tones options still showed. Fixed bug.
=> Tones Bug Fix

built-in_analyses.js, constraints/match.js, interface1.html, interface1.js, tableauMaker.js
Completes issue #98. I think all the match options are working correctly. I changed the text for custom match from the wireframe to say "Enforce Match only for syntactic categories that are..." instead of "Enforce Match only for XPs that are..." because I couldn't figure out how to update the text based on which categories are checked.
=> Adding match options to interface

constraints/noShift.js
Added alert message with noShift error message that is triggered when error is thrown. Should the error be somehow handled when it is caught, besides displaying the alert?
=> noShift error alert

interface1.html
Where do you want the info button? I put empty paragraphs before and after because it was overlapping the tree box but it does make the info button stick out
=> tree builder text hidden in an info button

analysis_html_files/Italian_BuiltIn_Analysis.html, built-in_analyses.js, constraints/binarity.js, constraints/match.js, interface1.html, interface1.js, trees/Italian_BuiltIn_Trees.js
* built-in analysis and save/load functionality now work with alignLeft_clitic
* built-in analysis and save/load functionality can now handle when a constraint has only one option. This was useful when I thought that requireMaximal was going to be an option on binMinLeaves
* built-in system code now refers to optionable constraints instead of just matchConstraints. Again, would have been useful if I could have used requireMaximal as an option for Italian built-in
* made Italian built-in system (Van Handel 2019) for NINJAL presentation
* updated a constraint definition to avoid redundancy
* interface now uses matchMaxSP, not matchMaxSyntax ([+maximal syntax, +maximal prosody] instead of [+maximal syntax, 0maximal prosody]). This is what was defined in the info button, it is what is needed …
=> AlignLeft_clitic built-in and Van Handel 2019 built-in for 2019

tableauMaker.js
"options" got initialized twice in makeTableau somehow. I have no clue why this only affected the built-in systems, but the tones are all working now for built-in systems and for non-built-in systems.
=> it was a scope issue

interface1.js
I kept the "done" button clearing "string of terminals", but now if trees have been added to the analysis, then gen does not take whatever is in "string of terminals" as input
=> Overriding terminals

interface1.js
in the tree-builder, terminals marked with -clitic become nodes with the category "clitic" rather than "x0" and the -clitic flag is removed from their id
=> -clitic becomes clitic category

interface1.html
I added info buttons for gen options with the info text from issue #265. I changed it from a table to divs so that the info content can display below the option name.
I left the "Only generate branching constituents" info empty for now because the option it needs to be changed (issue #264)
=> added info for gen options

analysis_html_files/markednessInteraction_SS_ES.html, constraints/recursiveCatEvals.js, tableauMaker.js, test/JapaneseHeadMarking.html, treeFormatting.js
Gives nodes the property "isHead" when they are heads as defined for the Japanese system. In parenthesize tree, gives heads an astrisk marking.
* I made it so that only-child terminals don't get an asterisk, although they still evaluate as being a head. I did this because they are clearly heads, though I can easily remove this feature.
* Note that, because GEN re-uses elements, the tableau maker will need to run markHeadsJapanese for each pTree _right_ before parenthesizing it. After the sCat conflation confusion, I am unsure how we want to implement this in makeTableau
=> Japanese head marking

inputCandidateGenerator.js, interface1.js, syntaxFilters.js, test/mirror_test.html
I think the "remove mirror images" option is working (issue #312)
I don't know if it's better to merge mirror-images into input-gen-options then merge input-gen-options into master or update mirror-images from input-gen-options and merge mirror-images to master.
=> Merge mirror-images into input-gen-options

interface1.html
Issue #365. I just reorganized the existing constraints. Should I add "show more/less" for the "match" or "align/wrap" fieldsets?
=> separated syntax-prosody mapping constraints in fieldsets

interface1.html, interface1.js
Addresses #373 . When intermediate syntactic category, terminal syntactic category or noUnary is selected, syntacticOpCompatible() checks that all the options are compatible. If not, it sets adjacentHeads to true and disables the input. If the options were previously incompatible and now aren't, syntacticOpCompatible re-enables adjacentHead and sets it back to what it was before the options were incompatible.
My thinking behind this is that someone might select noUnary, not see that it had selected adjacentHeads, and then deselect noUnary. In that case, the user would get adjacent heads where they would have expected not to.
=> Adjacent heads

built-in_analyses.js, inputCandidateGenerator.js, interface1.js
removed hard-coded XP root in addCliticsXP function to avoid [{one} [x.clitic]] behavior. Minimal string of "one" produces the following syntax trees:
1. | {one [x.clitic]}
2. | {[one] [x.clitic]}
This list would include {{one} [x.clitic]} and {{[one]} [x.clitic]} if not for a hard-coded exception since these structures are probably impossible (@rbibbs please confirm).
After implementing these changes, I was unable to reproduce the additional bug @rbibbs found where cp boundaries were omitted entirely.
=> Fix "Add XP clitics directly under root" bug

candidategenerator_wrapper.js, constraints/alignWrap.js, test/annotate_tones_test.html, treeFormatting.js
Change accent representation to be a boolean
Remaining issue: should we annotate nodes that have id 'a' with the .a suffix to mark them as accented?
=> Accent rep

test/_test_template.html, test/match_auto_testing.html
@M130 and I finished turning @nvh4 's test methods into automated tests using mocha. There is still some naming of tests to occur, but personally I would like feedback before editing all of the names.
Proposed naming scheme: describe blocks are labeled according to their corresponding tableau in @nvh4 's file, followed by a colon, followed by the syntax parameters (if any) that are being held constant in that test block. It blocks are named according to the varied prosody parameters.
Example:
...
=> Match Automated Testing

constraints/recursiveCatEvals.js
Small fix to issue where options.xxxx variable is called but options is not defined. Error ensues.
Simply added 
"""
options = options || {};
"""
so that options is defined.
=> Fix to markMinMax

interface1.html
... but without the changes to indentation that confused git so much in conjunction with changes to the info sections all over the place.
=> replicate "mapping vs. markedness macro-sections"

interface1.html, interface_JS/built-in_analyses.js
I set this up just as in your SPOT file, but please double check that everything looks ok before I merge this. In particular I wanted to confirm that it's okay that ES and SS aren't parameterized to any particular category since that was something that changed on the interface recently (after I re-read Myrberg 2013 more closely) and which I now realize I should have preserved as an option for backwards compatibility.
=> add Chamorro Align system for LSA2021

constraints/match.js, interface1.html
What do you think about adding a combined syntax <--> prosody mapping constraint to the interface? I am using it in my SS/ES investigation to cut down the complexity of the typology. This is analogous to a "symmetrical faithfulness" type of constraint Eric Bakovic was using in a talk I just heard from him (which i think was based on his AMP2020 paper with Anna Mai), which also had to do with special/general interactions in markedness. In that project, symmetrical FAITH was basically IDENT(Feature), but insofar as IDENT(F) is basically a combination of MAX(F) with DEP(F), and MatchSP is essentially MAX(phi) while MatchPS is essentially DEP(phi), the principle is the same. We can just keep it on the backend or demote it to the "Show more..." section if you think it's too odd to have up top. …
=> add matchSPPS (symmetrical FAITH for syntax-prosody)
